### ISSUE TITLE
Атлас в Карты

### ISSUE THREAD

**Issue by DIMINIRIMOTO** [xxxLEOPARDxxx/CSP_Thander#341]
Хочу чтоб это внесли в шип-пак для удобства пользователей, ибо есть квесты которые Атлас выкидывают в конец инвентаря, а так он будет всегда с нами, вот строчки кода:  		

                if (_mode == 1 && rItem.ItemType == "MAP" && ok2) continue;
		if (_mode == 2 && !ok && ok2) continue;
		ok = ok || rItem.ItemType == "MAP";
		if (_mode == 3 && ok && ok2) continue;
		if (_mode == 4)
               {
               if (rItem.id == "MapsAtlas") {}
              else 
              {
              if (rItem.ItemType != "MAP") continue;
              }
              }
        
        Правятся в: items.c с 746 по 756 строчку, с уважением: Kelse

**Comment by QwerrySt** [comment]
Можешь сделать сам, если код готов. Меняй файл и отправляй PullRequest.

**Comment by QwerrySt** [comment]
Первые четыре строчки у нас такие же. Править только mode4. 
То есть ты предлагаешь показывать Атлас на 4 вкладке инвентаря среди карт островов.

**Comment by VVV101** [comment]
Влито
